[package]
name = "rust-study-mod"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-crate = { path = "core-crate", version = "0.1.0" }